server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/first/**
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second/**

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
    health:
      show-details: always
