spring:
  application:
    name: second-microservice
server:
  port: 8082

  eureka:
    instance:
      hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
    health:
      show-details: always